Make trailing spaces count as errors
ranelpadon/ngram-type pull request #16
Opened 2022-05-15 16:35 UTC by udayvir-singh

fixes the problem when you type space at the end and it doesn't count as error until you have typed the next word, which fells very buggy.

For Example:
```
*-------------------*
* ll hi ll hi ll hi *
*-------------------*

ll_h_
```
won't count as error, until this much is typed:
```
ll_h_i
```

2022-05-16 16:32 UTC, ranelpadon commented
@udayvir-singh Thanks for your PR. Although I think this was similar to my original code:
https://github.com/ranelpadon/ngram-type/commit/264320652370041907a0a44f88b04f3f582f6c74

which is a fix to the trailing space's filed issue:
> There is a delay between typing the last character and advancing to the next test. If you type a space during this time (which is kinda natural) it causes an error instead and the test also fails to advance.
https://github.com/ranelpadon/ngram-type/issues/12

I could still accept your PR, but I'm thinking maybe we could also have a toggle-able option like `Ignore Trailing Space` which is enabled by default like the use case for #12. Then, you could set it to disabled (i.e. trailing space should be counted as error), for your use case. Wdyt?

2022-05-16 17:29 UTC, udayvir-singh commented
@ranelpadon
Thanks for reply, just added another commit that fixes problems with #12.

2022-08-06 16:11 UTC, ranelpadon commented
@udayvir-singh Sorry, I was quite busy recently, and just realized that your MR is fixing a bug while the phrase is not fully typed yet (mid part), unlike the #12 which is when the phrase is already typed (end part). I thought both of them were on the end parts that's why I was confused. They're indeed different scenarios, and both should work. Can you please open your MR again? Thanks

2022-08-06 16:15 UTC, ranelpadon commented on index.html
> +                    var typedPhrase = this.typedPhrase.replace(/^ +/, "");
Please use `.trimStart()` which is simpler/more readable:
`var typedPhrase = this.typedPhrase.trimStart()`

2022-08-06 16:16 UTC, ranelpadon commented on index.html
> +                    else if (this.expectedPhrase !== typedPhrase.replace(/ +$/, "")) {
Please use `.trimEnd()` which is simpler/more readable:
`else if (this.expectedPhrase !== typedPhrase.trimEnd()) {`

2022-08-06 16:17 UTC, ranelpadon commented on index.html
> +                    if (typedPhrase.replace(/ +$/, "") === this.expectedPhrase) {
Please use `.trimEnd()` which is simpler/more readable:
`if (typedPhrase.trimEnd() === this.expectedPhrase) {`

2022-08-06 16:18 UTC, ranelpadon requested changes
Done reviewing, changes look good. Just added some minor comments. Will merge once you update it. Thanks :)

2022-08-07 15:15 UTC, udayvir-singh commented
@ranelpadon I had deleted my fork so I can't make changes to this pull request.

I have opened another pull request from my new fork see #18.

2022-08-07 15:15 UTC, closed without merging

2022-08-07 15:22 UTC, ranelpadon commented
Ah I see, no worries. Will check the other MR. Thanks!